apiVersion: v1
kind: Service
metadata:
    labels:
        app: myapp
    name: app-service
spec:
    selector:
        app: myapp
    ports: 
        - protocol: TCP
          port: 8000
          targetPort: 8000
    type: NodePort

