apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/anilkumarnimisha/helm_backend.git
    targetRevision: HEAD 
    path: app-helm-charts
    helm:
      values: |
         image:
	   tag: "1.0"
         ingress: myapp-argo-application.$INGRESS_HOST.xip.io
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myweb-argo-application
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/anilkumarnimisha/helm_backend.git
    targetRevision: HEAD
    path: web-helm-charts
    helm:
      values: |
         image:
           tag: "1.0"
         ingress: myweb-argo-application.$INGRESS_HOST.xip.io
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
