apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        name: webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

