apiVersion: v1
kind: Service
metadata:
    labels:
        app: webapp
    name: web-service
spec:
    selector:
        app: webapp
    ports: 
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: {{ .Values.service.type }}

